set(WATER_BINARY_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(WATER_THIRD_LIBRARY_DIRECTORY ${CMAKE_SOURCE_DIR}/../lib)
set(WATER_THIRD_INCLUDE_DIRECTORY ${CMAKE_SOURCE_DIR}/../include)
set(WATER_LIB_VERSION  vc${MSVC_TOOLSET_VERSION})

include_directories(${CMAKE_SOURCE_DIR})
include_directories(${WATER_THIRD_INCLUDE_DIRECTORY})

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY FOLDER "DEFUALT")